### PR TITLE
#8 Fixed the issue

### PR DESCRIPTION
**Pull request by P-yiush07**
Now the circle is getting deleted according to 2 intersection points.

image

### CODE REVIEW

**Comment by bertyhell** [comment]
Hey Piyush

Thank for the PR.
It doesn't delete the whole circle now and the segment that is clicked is deleted.

But it also cuts the circle at all the other intersection points. The goal is to keep the rest of the circle as one entity.


as an example:
i draw 2 rectangles and an overlapping circle and click at the purple arrow:


current behavior: the segment closest to the purple arrow is deleted and the circle is cut at the 2 green arrows and at the 2 red arrows
image



expected result: the segment closest to the purple arrow is deleted and the circle is only cut at the 2 green arrows
image

**Comment by P-yiush07** [comment]
> Hey @P-yiush07
> 
> Thank for the PR. It doesn't delete the whole circle now and the segment that is clicked is deleted. That is good.
> 
> But it also cuts the circle at all the other intersection points. The goal is to keep the rest of the circle as one entity.
> 
> as an example: i draw 2 rectangles and an overlapping circle and click at the purple arrow:
> 
> current behavior: the segment closest to the purple arrow is deleted and the circle is cut at the 2 green arrows and at the 2 red arrows image
> 
> expected result: the segment closest to the purple arrow is deleted and the circle is only cut at the 2 green arrows image


Can you provide me more images for exact behaviour you want ?

**Comment by P-yiush07** [comment]
Check the current commit i made, in that i fixed the issue @bertyhell 

Screenshot 2024-09-30 232035

**Review by bertyhell — APPROVED** [review]

**Comment by bertyhell** [comment]
@P-yiush07 That works perfectly
Thx man :D

**Comment by bertyhell** [comment]
@P-yiush07 Are there any features you would like to see in this program?

I've made a list already in the readme: https://github.com/bertyhell/openwebcad#features
But if you have any suggestions i can add them to the readme

**Comment by P-yiush07** [comment]
> @P-yiush07 Are there any features you would like to see in this program?
> 
> I've made a list already in the readme: https://github.com/bertyhell/openwebcad#features But if you have any suggestions i can add them to the readme

I'll look up for this. Can we connect on linked in ? I've sent you request could you please check that and accept too 😀

**Pull request merged**
